---
- name: Install needrestart
  hosts: localhost
  tasks:
    - name: Install package
      ansible.builtin.package:
        name: needrestart
        state: present
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Add sudoers users to wheel group
      ansible.builtin.user:
        name: ansible
        groups: wheel
        append: true
        state: present
        createhome: false
